name: ai-entrainment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.24
  - networkx>=2.8
  - matplotlib>=3.7
  - mpmath>=1.3
  - sympy>=1.12
  - ipykernel
  - jupyterlab
  - pip

